version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://django:django123@db:5432/rapiddb
    networks:
      - roy-net

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rapiddb
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - roy-net

volumes:
  postgres_data:

networks:
  roy-net:
    driver: bridge
