apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 32080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
